SET foreign_key_checks = 0;

-- INSERT INTO `BACK`.`REPORT_STATUS` (`STATUS_ID`,`STATUS_NAME`) VALUES (1,'未處理');
-- INSERT INTO `BACK`.`REPORT_STATUS` (`STATUS_ID`,`STATUS_NAME`) VALUES (2,'已處理');
-- INSERT INTO `BACK`.`REPORT_STATUS` (`STATUS_ID`,`STATUS_NAME`) VALUES (3,'已略過');

-- INSERT INTO `BACK`.`REPORT_TYPE` (`TYPE_NAME`) VALUES ('裸露');
-- INSERT INTO `BACK`.`REPORT_TYPE` (`TYPE_NAME`) VALUES ('暴力');
-- INSERT INTO `BACK`.`REPORT_TYPE` (`TYPE_NAME`) VALUES ('騷擾');
-- INSERT INTO `BACK`.`REPORT_TYPE` (`TYPE_NAME`) VALUES ('自殺自殘');
-- INSERT INTO `BACK`.`REPORT_TYPE` (`TYPE_NAME`) VALUES ('垃圾訊息');
-- INSERT INTO `BACK`.`REPORT_TYPE` (`TYPE_NAME`) VALUES ('販售違禁品');
-- INSERT INTO `BACK`.`REPORT_TYPE` (`TYPE_NAME`) VALUES ('仇恨言論');
-- INSERT INTO `BACK`.`REPORT_TYPE` (`TYPE_NAME`) VALUES ('恐怖主義');
-- INSERT INTO `BACK`.`REPORT_TYPE` (`TYPE_NAME`) VALUES ('其它');


-- INSERT INTO `BACK`.`ADMIN` (`ADMIN_ID`,`ADMIN_ACCOUNT`,`ADMIN_PASSWORD`,`ADMIN_NAME`,`ADMIN_JOIN`,`ADMIN_LEVEL`,`ADMIN_STATUS`) VALUES (1,'jason871314','871314','Jason','2020-12-11 11:11:11.0',1,1);
-- INSERT INTO `BACK`.`ADMIN` (`ADMIN_ID`,`ADMIN_ACCOUNT`,`ADMIN_PASSWORD`,`ADMIN_NAME`,`ADMIN_JOIN`,`ADMIN_LEVEL`,`ADMIN_STATUS`) VALUES (2,'angela871314','880118','Angela','2020-12-11 11:11:11.0',1,1);
                                                                                                                                   --            
INSERT INTO `BACK`.`ARTICLE_REPORT` (`REPORT_NO`,`REPORTER_ID`,`ARTICLE_ID`,`REPORT_TYPE`,`REPORT_STATUS`,`REPORT_DESCRIPTION`,`REPORT_TIME`) VALUES (1,1,1,6,2,'廢文','2020-12-11 11:11:11.0');
INSERT INTO `BACK`.`REPLY_REPORT` (`REPORT_NO`,`REPORTER_ID`,`REPLY_ID`,`REPORT_TYPE`,`REPORT_STATUS`,`REPORT_DESCRIPTION`,`REPORT_TIME`) VALUES (1,1,1,8,2,'歧視原住民qq','2020-12-15 11:11:11.0');
INSERT INTO `BACK`.`GROUP_REPORT` (`REPORT_NO`,`REPORTER_ID`,`GROUP_ID`,`REPORT_TYPE`,`REPORT_STATUS`,`REPORT_DESCRIPTION`,`REPORT_TIME`) VALUES (1,1,1,2,2,'糾人尋仇','2020-12-12 11:11:11.0');
INSERT INTO `BACK`.`SINGLECHAT_REPORT` (`REPORT_NO`,`REPORTER_ID`,`MESSAGE_NO`,`REPORT_TYPE`,`REPORT_STATUS`,`REPORT_DESCRIPTION`,`REPORT_TIME`) VALUES (1,1,1,3,2,'騷擾','2020-12-13 11:11:11.0');
INSERT INTO `BACK`.`GROUPCHAT_REPORT` (`REPORT_NO`,`REPORTER_ID`,`MESSAGE_NO`,`REPORT_TYPE`,`REPORT_STATUS`,`REPORT_DESCRIPTION`,`REPORT_TIME`) VALUES (1,1,1,6,3,'貼亂碼亂群','2020-12-14 11:11:11.0');
INSERT INTO `BACK`.`INTRO_REPORT` (`REPORT_NO`,`REPORTER_ID`,`REPORTED_ID`,`REPORT_TYPE`,`REPORT_STATUS`,`REPORT_DESCRIPTION`,`REPORT_TIME`) VALUES (1,2,1,10,2,'假人','2020-12-15 11:11:11.0');

SET foreign_key_checks= 1;