SET foreign_key_checks = 0;

DELETE FROM `BACK`.`ADMIN`;
ALTER TABLE ADMIN AUTO_INCREMENT=0;

DELETE FROM `BACK`.`REPORT_STATUS`;
ALTER TABLE ADMIN AUTO_INCREMENT=0;

DELETE FROM `BACK`.`REPORT_TYPE`;
ALTER TABLE ADMIN AUTO_INCREMENT=0;

DELETE FROM `BACK`.`REPORT`;
ALTER TABLE ADMIN AUTO_INCREMENT=0;

SET foreign_key_checks= 1;