SET foreign_key_checks = 0;

DELETE FROM `BACK`.`ADMIN`;
ALTER TABLE ADMIN AUTO_INCREMENT=0;

DELETE FROM `BACK`.`ADMIN_LEVEL`;
ALTER TABLE `BACK`.`ADMIN_LEVEL` AUTO_INCREMENT=0;

DELETE FROM `BACK`.`ADMIN_STATUS`;
ALTER TABLE `BACK`.`ADMIN_STATUS` AUTO_INCREMENT=0;

DELETE FROM `BACK`.`OBJECT_TYPE`;
ALTER TABLE `BACK`.`OBJECT_TYPE` AUTO_INCREMENT=0;

DELETE FROM `BACK`.`REPORT_STATUS`;
ALTER TABLE `BACK`.`REPORT_STATUS` AUTO_INCREMENT=0;

DELETE FROM `BACK`.`REPORT_TYPE`;
ALTER TABLE `BACK`.`REPORT_TYPE` AUTO_INCREMENT=0;

DELETE FROM `BACK`.`REPORT`;
ALTER TABLE `BACK`.`REPORT` AUTO_INCREMENT=0;

SET foreign_key_checks= 1;